#pragma once

/* Old IDs stay renderable so an existing saved card keeps its appearance. */
#define FORTUNE_LEGACY_ART_COUNT 24576U
#define FORTUNE_FAMILY_COUNT 10U
#define FORTUNE_LAYOUT_COUNT 8U
#define FORTUNE_SCENE_COUNT (FORTUNE_FAMILY_COUNT * FORTUNE_LAYOUT_COUNT)
#define FORTUNE_SKIN_COUNT (FORTUNE_SCENE_COUNT * 4U)
#define FORTUNE_PALETTE_COUNT 6U
#define FORTUNE_NEW_ART_COUNT (FORTUNE_SKIN_COUNT * FORTUNE_PALETTE_COUNT)
#define FORTUNE_ART_COUNT (FORTUNE_LEGACY_ART_COUNT + FORTUNE_NEW_ART_COUNT)
