#pragma once
static const char *const FORTUNE_MOODS[] = {
    "随缘", "慢慢回血", "诗词留声", "生活观察", "冷幽默", "荒诞脑洞", "小见解", "关系切片", "小小出走"
};
#define FT_HOME "全库随机\n拆开一句话"
#define FT_HOME_HELP "确定抽签 · 上/下选主题"
#define FT_HOME_HINT "长确定打开签册 · 同轮不重复"
#define FT_TOPICS_HELP "上/下选择 · 确定抽签"
#define FT_TOPICS_HINT "长确定返回全库随机"
#define FT_REVEAL_HELP "上再抽 · 下换肤 · 确定收藏"
#define FT_REVEAL_HINT "长上音量 · 长下静音"
#define FT_SHOW_HELP "上再抽 · 下换肤 · 确定看签册"
#define FT_SHOW_HINT "长确定首页 · 长上音量"
#define FT_NO_PIN "还没有留下的签"
#define FT_EXHAUSTED "这组签已读完"
#define FT_EXHAUSTED_HINT "换主题 · 长按上洗牌"
#define FT_SAVING "正在留住这句话"
#define FT_SAVE_ERROR "未保存，断电可能丢失"
#define FT_INPUT_ERROR "按键未就绪，请重启"
#define FT_SOUND_ON "音效已开启 · 长下可静音"
#define FT_SOUND_OFF "已静音 · 长下可开启音效"
#define FT_SOUND_ERROR "声音暂不可用，抽签正常"
#define FT_VOLUME_CAPTION "调节即试听 · 保存后开启"
#define FT_VOLUME_HELP "上加 · 下减 · 确定保存"
#define FT_VOLUME_HINT "长确定取消"
#define FT_VOLUME_SAVED "音量已保存 · 长下可静音"
#define FT_ALBUM_EMPTY "签册还空着\n留住喜欢的话"
#define FT_ALBUM_HELP "上/下翻页 · 确定整理"
#define FT_ALBUM_HINT "长确定首页 · 长上音量"
#define FT_ALBUM_SAVED "已收藏，也已设为签名"
#define FT_ALBUM_UPDATED "已收藏过，外观已更新"
#define FT_ALBUM_PINNED "已设为签名"
#define FT_ALBUM_REMOVED "已移出签册 · 展示签名保留"
#define FT_ALBUM_REPLACE_HELP "上/下选旧签 · 确定替换"
#define FT_ALBUM_REPLACE_HINT "签册已满 · 长确定取消"
#define FT_ALBUM_CONFIRM_HELP "上/下选择 · 确定执行"
#define FT_ALBUM_CANCEL_HINT "长确定返回 · 默认取消"
