/* Generated by tools/pack_fortunes.py. Complete records, not templates. */
#pragma once
#include <stdint.h>
#define FORTUNE_COUNT 2112U
#define FORTUNE_BITS 11U
#define FORTUNE_DICTIONARY_COUNT 1558U
#define FORTUNE_PAYLOAD_BYTES 38674U
#define FORTUNE_CORPUS_ID 3420887641U
typedef struct { uint32_t bit_offset; uint8_t length, mood, style, reserved; } fortune_record_t;
extern const fortune_record_t FORTUNE_RECORDS[];
extern const uint16_t FORTUNE_DICTIONARY[];
extern const uint8_t FORTUNE_PAYLOAD[];
