/* Generated by tools/pack_fortunes.py. Complete records, not templates. */
#pragma once
#include <stdint.h>
#define FORTUNE_PREVIOUS_COUNT 312U
#define FORTUNE_PREVIOUS_BITS 10U
#define FORTUNE_PREVIOUS_DICTIONARY_COUNT 771U
#define FORTUNE_PREVIOUS_PAYLOAD_BYTES 6140U
#define FORTUNE_PREVIOUS_CORPUS_ID 3335999125U
#include "fortune_data.h"
extern const fortune_record_t FORTUNE_PREVIOUS_RECORDS[];
extern const uint16_t FORTUNE_PREVIOUS_DICTIONARY[];
extern const uint8_t FORTUNE_PREVIOUS_PAYLOAD[];
#define FORTUNE_PREVIOUS_SOURCE_COUNT 2200U
extern const uint32_t FORTUNE_PREVIOUS_MAP[];
