/* Generated by tools/pack_fortunes.py. Complete records, not templates. */
#pragma once
#include <stdint.h>
#define FORTUNE_LEGACY_COUNT 2112U
#define FORTUNE_LEGACY_BITS 11U
#define FORTUNE_LEGACY_DICTIONARY_COUNT 1558U
#define FORTUNE_LEGACY_PAYLOAD_BYTES 38674U
#define FORTUNE_LEGACY_CORPUS_ID 3420887641U
#include "fortune_data.h"
extern const fortune_record_t FORTUNE_LEGACY_RECORDS[];
extern const uint16_t FORTUNE_LEGACY_DICTIONARY[];
extern const uint8_t FORTUNE_LEGACY_PAYLOAD[];
