#!/usr/bin/env python3
"""Pack complete, independently authored UTF-8 records; never compose text."""
import argparse
import hashlib
import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def load_records(path):
    document = json.loads(path.read_text())
    records = [(g['mood'], g['style'], t) for g in document['groups'] for t in g['texts']]
    texts = [t for _, _, t in records]
    if not 1 <= len(texts) <= 16384 or len(set(texts)) != len(texts):
        raise ValueError('Require 1..16384 distinct complete records')
    for mood, style, text in records:
        if not 1 <= mood <= 8 or not 0 <= style < 3 or not 1 <= len(text) <= 32:
            raise ValueError('Invalid record metadata or length: ' + text)
        if any(ord(c) < 32 or 127 <= ord(c) <= 159 or 0xD800 <= ord(c) <= 0xDFFF or ord(c) > 65535 for c in text):
            raise ValueError('Only printable BMP characters are supported')
    return document, records


def array(name, kind, values):
    lines = [f'const {kind} {name}[] = {{']
    for i in range(0, len(values), 16):
        lines.append('    ' + ', '.join(str(v) for v in values[i:i+16]) + ',')
    return '\n'.join(lines) + '\n};\n'


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--release', action='store_true', help='enforce the current corpus production_minimum')
    args = p.parse_args()
    document, records = load_records(ROOT / 'assets/fortune/corpus.json')
    if args.release and len(records) < document['production_minimum']:
        raise SystemExit(f'Release blocked: {len(records)} independent records; require {document["production_minimum"]}+')
    codepoints = sorted({ord(c) for _, _, t in records for c in t})
    lookup = {cp: i for i, cp in enumerate(codepoints)}
    width = max(1, math.ceil(math.log2(len(codepoints))))
    payload = bytearray()
    bit_position = 0
    entries = []
    for mood, style, text in records:
        entries.append((bit_position, len(text), mood, style))
        for c in text:
            value = lookup[ord(c)]
            for b in range(width):
                byte = bit_position // 8
                if byte == len(payload):
                    payload.append(0)
                payload[byte] |= ((value >> b) & 1) << (bit_position % 8)
                bit_position += 1
    raw = b''.join(t.encode() + b'\0' for _, _, t in records)
    identity = int.from_bytes(hashlib.sha256(json.dumps(records, ensure_ascii=False).encode()).digest()[:4], 'little')
    header = f'''/* Generated by tools/pack_fortunes.py. Complete records, not templates. */
#pragma once
#include <stdint.h>
#define FORTUNE_COUNT {len(records)}U
#define FORTUNE_BITS {width}U
#define FORTUNE_DICTIONARY_COUNT {len(codepoints)}U
#define FORTUNE_PAYLOAD_BYTES {len(payload)}U
#define FORTUNE_CORPUS_ID {identity}U
typedef struct {{ uint32_t bit_offset; uint8_t length, mood, style, reserved; }} fortune_record_t;
extern const fortune_record_t FORTUNE_RECORDS[];
extern const uint16_t FORTUNE_DICTIONARY[];
extern const uint8_t FORTUNE_PAYLOAD[];
'''
    source = '#include "fortune_data.h"\n' + array('FORTUNE_DICTIONARY', 'uint16_t', codepoints)
    source += array('FORTUNE_PAYLOAD', 'uint8_t', list(payload))
    source += 'const fortune_record_t FORTUNE_RECORDS[] = {\n'
    source += ''.join(f'    {{{off}, {n}, {mood}, {style}, 0}},\n' for off, n, mood, style in entries) + '};\n'
    (ROOT / 'main/fortune_data.h').write_text(header)
    (ROOT / 'main/fortune_data.c').write_text(source)
    report = {'stage': document['stage'], 'independent_records': len(records),
              'release_ready': len(records) >= document['production_minimum'], 'utf8_bytes': len(raw),
              'packed_text_bytes': len(payload), 'dictionary_bytes': len(codepoints)*2,
              'index_metadata_bytes': len(records)*8, 'bits_per_character': width,
              'corpus_id': identity}
    (ROOT / 'assets/fortune/packing-report.json').write_text(json.dumps(report, indent=2) + '\n')
    print(json.dumps(report))


if __name__ == '__main__':
    main()
