#!/usr/bin/env python3
"""Pack complete, independently authored UTF-8 records; never compose text."""
import argparse
import hashlib
import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def load_records(path):
    document = json.loads(path.read_text())
    records = [(g['mood'], g['style'], t) for g in document['groups'] for t in g['texts']]
    texts = [t for _, _, t in records]
    if not 1 <= len(texts) <= 16384 or len(set(texts)) != len(texts):
        raise ValueError('Require 1..16384 distinct complete records')
    for mood, style, text in records:
        if not 1 <= mood <= 8 or not 0 <= style < 3 or not 1 <= len(text) <= 32:
            raise ValueError('Invalid record metadata or length: ' + text)
        if any(ord(c) < 32 or 127 <= ord(c) <= 159 or 0xD800 <= ord(c) <= 0xDFFF or ord(c) > 65535 for c in text):
            raise ValueError('Only printable BMP characters are supported')
    return document, records


def array(name, kind, values):
    lines = [f'const {kind} {name}[] = {{']
    for i in range(0, len(values), 16):
        lines.append('    ' + ', '.join(str(v) for v in values[i:i+16]) + ',')
    return '\n'.join(lines) + '\n};\n'


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--release', action='store_true', help='enforce the current corpus production_minimum')
    args = p.parse_args()
    document, records = load_records(ROOT / 'assets/fortune/corpus.json')
    if args.release and len(records) < document['production_minimum']:
        raise SystemExit(f'Release blocked: {len(records)} independent records; require {document["production_minimum"]}+')
    write_bank(document, records)
    legacy, old_records = load_records(ROOT / 'assets/fortune/legacy-corpus.json')
    write_bank(legacy, old_records, legacy=True)
    previous, previous_records = load_records(ROOT / 'assets/fortune/previous-corpus.json')
    new_ids = {t: i for i, (_, _, t) in enumerate(records)}
    retired = [r for r in previous_records if r[2] not in new_ids]
    retired_ids = {t: i for i, (_, _, t) in enumerate(retired)}
    mapping = [new_ids[t] if t in new_ids else 0x40000000 | retired_ids[t]
               for _, _, t in previous_records]
    write_bank(previous, retired, previous=True, identity_records=previous_records)
    header_path = ROOT / 'main/fortune_previous_data.h'
    header_path.write_text(header_path.read_text() +
                          f'#define FORTUNE_PREVIOUS_SOURCE_COUNT {len(previous_records)}U\n'
                          'extern const uint32_t FORTUNE_PREVIOUS_MAP[];\n')
    source_path = ROOT / 'main/fortune_previous_data.c'
    source_path.write_text(source_path.read_text() + array('FORTUNE_PREVIOUS_MAP', 'uint32_t', mapping))


def write_bank(document, records, legacy=False, previous=False, identity_records=None):
    prefix = 'FORTUNE_PREVIOUS' if previous else 'FORTUNE_LEGACY' if legacy else 'FORTUNE'
    basename = 'fortune_previous_data' if previous else 'fortune_legacy_data' if legacy else 'fortune_data'
    citations = document.get('citations', {})
    captions = ['']
    caption_ids = {}
    for text, citation in citations.items():
        caption = citation['display']
        if caption not in captions:
            captions.append(caption)
        caption_ids[text] = captions.index(caption)
    if len(captions) > 256:
        raise ValueError('Citation index exceeds one byte')
    codepoints = sorted({ord(c) for _, _, t in records for c in t})
    lookup = {cp: i for i, cp in enumerate(codepoints)}
    width = max(1, math.ceil(math.log2(len(codepoints))))
    payload = bytearray()
    bit_position = 0
    entries = []
    for mood, style, text in records:
        entries.append((bit_position, len(text), mood, style, caption_ids.get(text, 0)))
        for c in text:
            value = lookup[ord(c)]
            for b in range(width):
                byte = bit_position // 8
                if byte == len(payload):
                    payload.append(0)
                payload[byte] |= ((value >> b) & 1) << (bit_position % 8)
                bit_position += 1
    raw = b''.join(t.encode() + b'\0' for _, _, t in records)
    identity_records = records if identity_records is None else identity_records
    identity = int.from_bytes(hashlib.sha256(json.dumps(identity_records, ensure_ascii=False).encode()).digest()[:4], 'little')
    if citations:
        identity = int.from_bytes(hashlib.sha256(json.dumps([identity_records, citations], ensure_ascii=False).encode()).digest()[:4], 'little')
    header = f'''/* Generated by tools/pack_fortunes.py. Complete records, not templates. */
#pragma once
#include <stdint.h>
#define {prefix}_COUNT {len(records)}U
#define {prefix}_BITS {width}U
#define {prefix}_DICTIONARY_COUNT {len(codepoints)}U
#define {prefix}_PAYLOAD_BYTES {len(payload)}U
#define {prefix}_CORPUS_ID {identity}U
{ '#include "fortune_data.h"' if legacy or previous else 'typedef struct { uint32_t bit_offset; uint8_t length, mood, style, citation; } fortune_record_t;' }
extern const fortune_record_t {prefix}_RECORDS[];
extern const uint16_t {prefix}_DICTIONARY[];
extern const uint8_t {prefix}_PAYLOAD[];
'''
    source = f'#include "{basename}.h"\n' + array(prefix+'_DICTIONARY', 'uint16_t', codepoints)
    source += array(prefix+'_PAYLOAD', 'uint8_t', list(payload))
    source += f'const fortune_record_t {prefix}_RECORDS[] = {{\n'
    source += ''.join(f'    {{{off}, {n}, {mood}, {style}, {cite}}},\n' for off, n, mood, style, cite in entries) + '};\n'
    if not legacy and not previous:
        header += 'extern const char *const FORTUNE_CITATIONS[];\nextern const uint16_t FORTUNE_RETAINED_IDS[];\n'
        source += 'const char *const FORTUNE_CITATIONS[] = {\n'
        source += ''.join('    '+json.dumps(c, ensure_ascii=False)+',\n' for c in captions)+'};\n'
        counts = [0] + [sum(m==i for m,_,_ in records) for i in range(1,9)]
        if document['theme_percentages'] != [20,10,15,15,15,10,10,5] or len(records)%20 or not all(
                counts[i] == document['theme_percentages'][i-1]*len(records)//100 for i in range(1,9)):
            raise ValueError('Balanced 20-card blocks require exact 20/10/15/15/15/10/10/5 quotas')
        offsets = [0] + [sum(counts[:i]) for i in range(1,9)]
        if not all(records[offsets[i]+j][0]==i for i in range(1,9) for j in range(counts[i])):
            raise ValueError('Theme records must be stored contiguously')
        header += 'extern const uint16_t FORTUNE_THEME_OFFSETS[], FORTUNE_THEME_COUNTS[];\n'
        source += array('FORTUNE_THEME_OFFSETS','uint16_t',offsets)
        source += array('FORTUNE_THEME_COUNTS','uint16_t',counts)
        source += array('FORTUNE_RETAINED_IDS', 'uint16_t', [document.get('legacy_ids', {}).get(t,65535) for _,_,t in records])
    (ROOT / f'main/{basename}.h').write_text(header)
    (ROOT / f'main/{basename}.c').write_text(source)
    report = {'stage': document['stage'], 'independent_records': len(records),
              'release_ready': len(records) >= document['production_minimum'], 'utf8_bytes': len(raw),
              'packed_text_bytes': len(payload), 'dictionary_bytes': len(codepoints)*2,
              'index_metadata_bytes': len(records)*8, 'bits_per_character': width,
              'corpus_id': identity}
    report['citation_utf8_bytes'] = sum(len(c.encode())+1 for c in captions) if not legacy and not previous else 0
    (ROOT / ('assets/fortune/previous-packing-report.json' if previous else 'assets/fortune/legacy-packing-report.json' if legacy else 'assets/fortune/packing-report.json')).write_text(json.dumps(report, indent=2) + '\n')
    print(json.dumps(report))


if __name__ == '__main__':
    main()
